### ISSUE TITLE
crash while launching Minecraft

### ISSUE THREAD

**Issue by Hypsellis** [TeamWizardry/TMT-Refraction#11]
I still get a crash at the lauching while I updated to the 1.2 version. http://pastebin.com/GJ34GkgE

**Comment by LordSaad44** [comment]
What version of liblib are you using?

**Comment by Hypsellis** [comment]
I just tried with the last one.

**Comment by LordSaad44** [comment]
Seems to be a liblib issue. @yrsegal

**Comment by LordSaad44** [comment]
Hopefully fixed.
