### ISSUE TITLE
Server crash when assembling Laser Assembly Table

### ISSUE THREAD

**Issue by Riyshn** [TeamWizardry/TMT-Refraction#14]
As title. Crash happened when placing the final Light Beam Diverging Cell above the Light Beam Dilation Device as instructed by the info tablet. The crash does not happen on a local/single player world.

As far as I can tell the crash is rendering-related. At the least, it did not seem to reoccur until a player logged back in, at which point it would crash again repeatedly, effectively killing the world.

http://pastebin.com/GJ34GkgE

**Comment by yrsegal** [comment]
not aGAIN

**Comment by LordSaad44** [comment]
Fixed.
