### ISSUE TITLE
Crash on Server Load

### ISSUE THREAD

**Issue by Towsty** [TeamWizardry/TMT-Refraction#2]
Crashed loading latest refraction on Forge 2123 server.

Crash Report:
https://gist.github.com/Towsty/41cfd98a63ac7c7c2e51379f78a82ad7
Server Log:
https://gist.github.com/Towsty/74c34abc6d721f6734d2663b5555b824

**Comment by LordSaad44** [comment]
Fixed.

**Comment by AnZaNaMa** [comment]
When can we expect the next release to fix this? I'm super hyped for this mod but can't run it on my server. I tried just building it from source, but it gave me another error.

**Comment by Saereth** [comment]
We'd really love to include this on our server, do you have a jenkins or nightly build we could get the fixed version from without waiting for a curseforge publish?

**Comment by Eladkay** [comment]
I'll get you a fresh build. Warning: not thoroughly tested.

**Comment by Saereth** [comment]
fair enough, sounds good!

**Comment by Eladkay** [comment]
Here you go: http://www.mediafire.com/file/6dydgodeoh16v27/refraction-1.0.jar

**Comment by LordSaad44** [comment]
@Towsty @AnZaNaMa We've all been extremely busy lately. We've been working hard on getting the next release ready. The changelog is massive already but you should expect a release this week. Sorry for the long delay!
