### ISSUE TITLE
Can't reload laser cartridges

### ISSUE THREAD

**Issue by CJL48** [TeamWizardry/TMT-Refraction#22]
Just what the issue says: putting the cartridges in the path of a laser doesn't refill them, and neither does putting them back into the mod's crafting table. The manual doesn't mention reloading or refilling them either, and they can't be turned back into blank cartridges.

Refraction 1.3.2
LibrarianLib 1.8
Forge 12.18.3.2185
Minecraft 1.10.2

**Comment by LordSaad44** [comment]
Picture of your setup please. Also you put any cartridge into the assembly table, feed a laser into the block, and power the table to fill the cartridge with that color.

**Comment by CJL48** [comment]
Feeding a laser into the assembly table ONLY works if the cartridge is newly created.
Otherwise, nothing happens. I did test this with a fresh install, containing only Forge, LibrarianLib, and Refraction, but the screenshot is from my main instance. Note the yellow cartridge, and the lack of particle effects.
![2017-01-08_13 43 40](https://cloud.githubusercontent.com/assets/8433790/21752566/900d4e30-d5a8-11e6-93dc-0cb29e0517bd.png)

**Comment by LordSaad44** [comment]
Try this: Put at least a one block space between the assembly table and the yellow lens. Let me know the results.

**Comment by CJL48** [comment]
A block space of distance between the filter and assembly table didn't help. Neither does using a survival setup (electric lasers, prism, and mirrors).

**Comment by Rucoon** [comment]
I can also say this does not work for me.

**Comment by LordSaad44** [comment]
Already charged cartridges are now able to be recharged. I was checking nbt accidentally for the color consuming recipies. Fixed.
