### ISSUE TITLE
Pink laser can not place seeds

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#23]
This was shown to work back when the mod was first being teased but does not seem to work anymore. Is this a bug or was it just removed?

**Comment by yrsegal** [comment]
It ought to be able to right click any item. Can we see a screenshot of the setup?

**Comment by Rucoon** [comment]
http://i.imgur.com/Q8uSHZO.png I also tried it from above but that did not seem to work.

**Comment by LordSaad44** [comment]
I'll see what I can do.

**Comment by LordSaad44** [comment]
Fixed.
