### ISSUE TITLE
No effective tool for a few blocks

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#24]
Lenses, disco balls, prisms, sensors, fiber cables, beam translocators and AFDQTAs have not effective tool for mining so they are really annoying to remove, any plans for adding one or having the screwdriver be able to pick them up?

**Comment by yrsegal** [comment]
I like the screwdriver idea. AFDQTAs, Translocators, Fiber Cables, and Sensors can have pickaxes set as effective, though.

**Comment by yrsegal** [comment]
c982bc3c6c02198fc9a535f218d7b67c66a64103
