### ISSUE TITLE
InGame Guide Font Resize Issue

### ISSUE THREAD

**Issue by DnielMC** [TeamWizardry/TMT-Refraction#25]
Pretty much that. That's the biggest size I can go, but the text is unreadable.
The text is just to small.

![2017-01-14_13 15 32](https://cloud.githubusercontent.com/assets/9432406/21959101/53b624d8-dabd-11e6-8495-af429336a830.png)

**Comment by LordSaad44** [comment]
Try setting gui size to large in your video settings.

**Comment by DnielMC** [comment]
Well, already tried that.. Also tried on Fullscreen (not just large screen on the screenshot)
Nothing working..
Maybe it's my Resolution? I only have 1600x900.

**Comment by thecodewarrior** [comment]
Saad, I built in a way for you to dynamically resize the GUI, but you don't use it. This is what happens when you make enormous GUIs.

**Comment by LordSaad44** [comment]
@thecodewarrior I set the GUI size to its actual size in the super method. You said that would auto size and it is. It's working in most cases except this. What else must I do? Check screen res and scale the comp accordingly?

**Comment by thecodewarrior** [comment]
use GuiBase.adjustGuiSize() to change the comp size based on the size of the gui, yes.

**Comment by LordSaad44** [comment]
Fixed. http://imgur.com/CxfhQr0
