### ISSUE TITLE
Minetweaker Support does not remove recipes from JEI

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#26]
When removing a item with Minetweaker let say: `mods.refraction.AssemblyTable.remove(<refraction:electric_laser>);`
It will leave a phantom recipe in JEI that can not be used.

**Comment by Eladkay** [comment]
The JEI API allows for removing of recipes, even though I recommend making it a proxy method of some sorts to make sure you don't get noclassdeffoundexceptions if there's no jei

**Comment by yrsegal** [comment]
Refraction depends on JEI, iirc

**Comment by LordSaad44** [comment]
@yrsegal no longer does

**Comment by yrsegal** [comment]
Ah. However, this just requires the JEI recipe list for assembly to be
rebuildable every time the plugin fires.

**Comment by LordSaad44** [comment]
@yrsegal idk how to do that... so.. @murapix ?

**Comment by al132** [comment]
There were some API changes that affected everyone using crafttweaker integration, but it's a pretty simple fix. Look at [this](https://github.com/TechReborn/TechReborn/commit/7ae3ab5d87a24d2ae48f83b78626d3db7943f8bf) commit for an example

**Comment by LordSaad44** [comment]
Fixed. (i hope)
