### ISSUE TITLE
Alloy armor indestructible

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#29]
The alloy armor seems to take no damage at all, not showing any damage bar or damage tool tip.

**Comment by LordSaad44** [comment]
@murapix @yrsegal e_e how fix

**Comment by Eladkay** [comment]
by removing the todo and making it do stuff?

**Comment by Eladkay** [comment]
https://github.com/TeamWizardry/TMT-Refraction/blob/master/src/main/java/com/teamwizardry/refraction/common/item/armor/ItemArmorReflectiveAlloy.java#L94

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
