### ISSUE TITLE
[Request] In-game documentation

### ISSUE THREAD

**Issue by InjuredWolf** [TeamWizardry/TMT-Refraction#30]
Being honest, I have no idea how to use this mod, aside from just throwing things together in Creative. Some form of documentation (a wiki or in-game book) would be super handy.

**Comment by Eladkay** [comment]
I'm pretty sure we have a book

**Comment by LordSaad44** [comment]
Search for the information tablet in the creative menu.

**Comment by InjuredWolf** [comment]
Didn't see it in JEI. Will check again, though.
