### ISSUE TITLE
NullPointerException when rotating mirror

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [TeamWizardry/TMT-Refraction#33]
https://gist.github.com/Aedda/b35beffebb3fba5a186287f05fc13eac

I place a mirror under a Light Beam Dilation Device and rotate it 270 degrees on the y axis. The instant I rotate it 45 degrees on the x axis the server crashes due to this NPE. It seems to happen wherever I do this exact procedure.

**Comment by yrsegal** [comment]
r.data is null. I think this is codewarrior's stuff?

**Comment by LordSaad44** [comment]
Fixed.
