### ISSUE TITLE
Crash! 1.10.2 F2221

### ISSUE THREAD

**Issue by Rickydou** [TeamWizardry/TMT-Refraction#34]
Ktk Modpack
https://gist.github.com/Rickydou/aa4d9eaecf90573c7fef9868ef1b5e75
librarianlib-1.9 + Forgelin-1.2.0 = Ok + refraction-1.3.3 = Crash
Or
librarianlib-1.8 + Forgelin-1.2.0 + refraction-1.3.3 = Ok

Server Test 3 mods only img --> http://imgur.com/a/cNWzQ = Crash!

So thank you kindly help me ;)

**Comment by Eladkay** [comment]
Yeah now it's totally @yrsegal and I fixed it you can thank me bye

**Comment by Rickydou** [comment]
https://gist.github.com/Rickydou/01fab4e0d74f21de09142769b201937c
Sorry French ..

I download new and replace with care, remove the world .. but the server then stops if its can help you and thank you for lifting point ;)
