### ISSUE TITLE
Crafttweaker recipes need more explaining...

### ISSUE THREAD

**Issue by JAWSAWN** [TeamWizardry/TMT-Refraction#36]
Tried doing mods.refraction.AssemblyTable.addRecipe(name, <extrautils2:ingredients>, {<minecraft:redstone>,<minecraft:redstone>,<minecraft:redstone>,<minecraft:redstone>,<extrautils2:endershard>} , "16", "32", "255", "255", "0", "0", "0", "0")

but no idea what "name" stands for and wonder what is the correct way to insert numbers and inputs/outputs

**Comment by yrsegal** [comment]
Name is just whatever you want, that should probably be internalized to something along the lines of "mtrecipe{hash of ingredients}" so that we don't force the scriptmaker to know what that means @murapix

**Comment by JAWSAWN** [comment]
For future ref:
mods.refraction.AssemblyTable.addRecipe("name", <minecraft:glowstone_dust>, [<minecraft:redstone>,<minecraft:gunpowder>] , 16, 32, 255, 255, 0, 0, 0, 0);
 Also modtweaker was required to do this.
