### ISSUE TITLE
Fatal Error Occuring with Solar Assembly Table

### ISSUE THREAD

**Issue by DesiresTM** [TeamWizardry/TMT-Refraction#38]
So the error is occurring whenever I construct the Solar Assembly Table Multi structure. At night it seems fine, however whenever it turns morning and anyone is in the chunk, it throws a Fatal Error. The modpack is called ATM : Illumination, however they said to post on the modpack github. The odd part is that it doesn't show much in an error report.

This error is occurring with anyone in the chunk.

https://hastebin.com/lubilibegu.swift

There is also an fatal error being thrown when placing reflective ingots into the Assembly table itself.

**Comment by Eladkay** [comment]
Haha good luck with that, it's a vanilla error

**Comment by DesiresTM** [comment]
Even if this is only occurring with the Assembly Table?

**Comment by LordSaad44** [comment]
@DesiresTM elad is correct, these seems to be an error with packets. please post the versions of liblib and refraction you're using and tell me the EXACT way you built your structure and on what. Is it on multiplayer or singleplayer?

**Comment by DesiresTM** [comment]
The version of Refraction we are using is Refraction-1.3.4.jar.
How I'm building the structure is the exact model that is provided in a book. Assembly table in middle of a 3by3 block, one block of air, magnifying glass and then the slabbed glass in a 3by3 above that. It's placed on grass outside.

We are running multiplayer, yes. Where do you find version of lib? If I think it's what you mean, I'm running LibriarianLib and it's on Libriarianlib-1.10.1.jar

**Comment by DesiresTM** [comment]
We updated forge, apparently that was the issue. Thank you!

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
