### ISSUE TITLE
Information Tablet errors

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamWizardry/TMT-Refraction#39]
See images for issues. I circled examples in yellow.

![temp1](https://cloud.githubusercontent.com/assets/13642054/23508896/97c8d5fa-ff4b-11e6-99da-7be998aa83b7.png)

**Comment by LordSaad44** [comment]
I don't get these issues indev... Show me a list of mods installed.

**Comment by VallenFrostweaver** [comment]
Here you go
![temp1](https://cloud.githubusercontent.com/assets/13642054/23511586/7bed3524-ff55-11e6-83bb-5d6d9f283ff5.png)

**Comment by LordSaad44** [comment]
update forge?

**Comment by LordSaad44** [comment]
@VallenFrostweaver has updating forge fixed your issue? I can't reproduce this.

**Comment by yrsegal** [comment]
Do you have the § character in the lang? that can cause this

**Comment by LordSaad44** [comment]
no I'm using & and textformatting
