### ISSUE TITLE
TLTPrism recipe error

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamWizardry/TMT-Refraction#40]
Upon using 5 or more mirrors I can't craft the TLTPrism but using 2,3, or 4 I can. The instruction book states I need a minimum of 5 mirrors.

**Comment by LordSaad44** [comment]
recipies got changed and are getting changed in the next update. very sorry for the inconvenience.

**Comment by VallenFrostweaver** [comment]
No worries. Just trying to make things from the manual.

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
