### ISSUE TITLE
Information Tablet incomplete

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamWizardry/TMT-Refraction#41]
Under the topic "merging" it just stops mid sentence. See image for reference.
![temp1](https://cloud.githubusercontent.com/assets/13642054/23510881/30675898-ff53-11e6-9d64-9a16dd83be8c.png)

**Comment by LordSaad44** [comment]
already reported, getting fixed in the next update. if you need aid with this, ask us on the discord and we'll guide you.

**Comment by VallenFrostweaver** [comment]
ok
