### ISSUE TITLE
Massive lags

### ISSUE THREAD

**Issue by scrinpwnz** [TeamWizardry/TMT-Refraction#42]
Looks like this mod is causing lags on our server. ~4 hours after reboot, you can see this in the server logs:
![lags](https://cloud.githubusercontent.com/assets/23394864/24078392/d1532c20-0c9e-11e7-82ac-be40338f4a6f.png)
The WarmRoast show the following:
![warmroast](https://cloud.githubusercontent.com/assets/23394864/24078398/fae7bd9e-0c9e-11e7-9289-90970710ea3b.png)

refraction-1.3.4
forge-1.10.2-12.18.3.2254-universal
minecraft_server.1.10.2

Here full logs from WarmRoast
[WarmRoast.zip](https://github.com/TeamWizardry/TMT-Refraction/files/853029/WarmRoast.zip)

**Comment by LordSaad44** [comment]
That's... impossible...

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
