### ISSUE TITLE
Missing guide

### ISSUE THREAD

**Issue by basmulder03** [TeamWizardry/TMT-Refraction#43]
![2017-04-10_17 14 09](https://cloud.githubusercontent.com/assets/20653542/24869942/11aff046-1e15-11e7-8585-861cee3db830.png)
Missing guide in the information tablet. 

Modpack: Skyexchange lite 2

**Comment by basmulder03** [comment]
I'm on version 1.3.4

**Comment by tregeiw2** [comment]
*bump*

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
