### ISSUE TITLE
Electric Laser not accepting energy

### ISSUE THREAD

**Issue by racer290** [TeamWizardry/TMT-Refraction#44]
I have tried to get an electric laser running, but it refused to accept energy. I have tried Actually Addition Energy Lasers, EnderIO Conduits and Mekanism Universal Cables. The cables and conduits did not even connect to the laser block. I put them on different faces, none of them worked.

**Comment by LordSaad44** [comment]
This block is to be removed in future updates. Sorry.

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
