### ISSUE TITLE
Disco Ball causing client disconnect

### ISSUE THREAD

**Issue by mathwiz617** [TeamWizardry/TMT-Refraction#46]
When I powered a disco ball with a redstone signal and white light from a creative laser, it disconnected everybody on the server who had it rendered.

There was no crash, just "A fatal error has occurred, this connection has been terminated."

What's more, it continued to disconnect everyone who logged on near it. We tried removing the disco ball with worldedit, but that didn't work. We ended up removing the mod from our server just to remove the disco ball.

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
