### ISSUE TITLE
Electron Excitation Chamber misbehaving?

### ISSUE THREAD

**Issue by static7s** [TeamWizardry/TMT-Refraction#47]
The Electron Excitation Chamber(from here on, EEC) isn't behaving the way one would expect it to based on the contents of the in-game documentation. No light bridge is produced when two directly adjacent  EECs are hit with parallel cyan laser beams, _UNLESS_ the beams are colored using the creative cyan filter. Whether its cyan light from passing through a block of cyan stained glass(which doesn't attract entities), or a cyan laser produced with the Light Beam Coalescing Cube (which, I confirmed, attracts entities), no light bridge results. Additionally, I have discovered that there are cases where a light bridge won't (...properly) form even _with_ the creative cyan filter. Admittedly, my image doesn't give a clear view of what I did to make it happen, but I'll just tell you that the setup is 4 rows of:
creative laser->creative cyan filter-> 2 lenses-> any number of air blocks(within reason :p) ->EEC
![2017-05-06_21 26 12](https://cloud.githubusercontent.com/assets/7786502/25782485/1521cdca-331a-11e7-83a9-4ff779b96458.png)
As you can see, what happens in that case is...odd, to say the least. And just to be sure, I did check, and it isn't just a case of the bridge not rendering as it should; The 1 by 4 area directly in front of the EECs that looks like a light bridge is solid, and the part that looks like a cyan laser beam are not solid, and pull entities towards the lasers(because they are, in fact, somehow still cyan laser beams).

**Comment by InjuredWolf** [comment]
My guess is that once the first block is converted to a light bridge, it stops checking the lasers because the laser isn't actually hitting the EEC. A check would be needed for that, I suppose? maybe in the light bridge block itself? would need a direction (east-west, north-south, up-down?) to prevent creating corners, but ah well.

**Comment by static7s** [comment]
And about it not working unless the lasers are colored using the creative filters?

**Comment by LordSaad44** [comment]
Sorry, but refraction 1 is discontinued. Refraction 2 is going to be a thing in the future however. Super sorry. :(

**Comment by InjuredWolf** [comment]
Welp, I look forward to seeing it. Will it be in 1.10.2 at all, or will it only be for future versions?
