### ISSUE TITLE
1.10.2 Refraction Tablet not working at all

### ISSUE THREAD

**Issue by Zygus42** [TeamWizardry/TMT-Refraction#49]
refraction-1.3.4
librarianlib-1.8
forge-1.11.2-13.18.3.2254

The Refraction Tablet is not working at all on out server.  When I tried a test install with no other mods, it crashed, so I'm guessing something on our server is protecting us from the crash:

[crash-2017-06-06_12.30.30-client.txt](https://github.com/TeamWizardry/TMT-Refraction/files/1053828/crash-2017-06-06_12.30.30-client.txt)

**Comment by Zygus42** [comment]
Another test with
refraction-1.3.4
librarianlib-1.10.1
Forgelin-1.4.2

Does work - reason we were using an old version of librarianlib is that forgelin was crashing our server, and this version still does - have tried every version of forgelin, and it continues to crash out server on startup:

[crash-2017-06-06_12.40.06-server.txt](https://github.com/TeamWizardry/TMT-Refraction/files/1053841/crash-2017-06-06_12.40.06-server.txt)

**Comment by Zygus42** [comment]
Sorry, noticed my last comment was a bit incoherent - it worked fine in singleplayer with Forgelin, but the server crashes on startup.  Without Forgelin and using an older version of librarianlib, it doesn't crash the server but the tablet doesn't work or if no other mods are installed, it crashed when you try to use the tablet.

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
