### ISSUE TITLE
[Request if not currently a thing] Portal Gun Support

### ISSUE THREAD

**Issue by InjuredWolf** [TeamWizardry/TMT-Refraction#51]
If they don't already, can the lasers be made to go through the portals from Portal Gun (by iChun)? Would be kinda neat, especially if you could make it work with the light bridges from the EEC as well.

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!

Also: i wont add any more features, i am just maintaining/bugfix stuff
