### ISSUE TITLE
Light beam coalescing cube 

### ISSUE THREAD

**Issue by freddiericci** [TeamWizardry/TMT-Refraction#52]
Hi!
Could you please add a small explanation about the recipes?
I want to craft a light beam coalescing cube and don't knwo what i have to set up with those laser colors?
I dont understand the amount of lasers and which if i only need colored ones or full spectrum, too.

I really want to craft the resonating Redstone crystals by I have to go threw all of this so please help me do it it’s for a mod back called skyexchange 2 lite

**Comment by freddiericci** [comment]
How many beams do I need and I have had both red and green on the assembly table with a Redstone torch it did nothing

**Comment by Rikshy** [comment]
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!
