### ISSUE TITLE
[1.12] Crash from / by zero

### ISSUE THREAD

**Issue by ProxyPlayerHD** [TeamWizardry/TMT-Refraction#53]
[LOG](https://pastebin.com/exHhDh6g)

All i did was this (pic below), and started to place the red green and blue filters on the same colored wool, which almost instantly crashed the game with this log
![2018-07-16_17 32 12](https://user-images.githubusercontent.com/13576843/42767863-5701206e-891e-11e8-834f-3314c7366ced.png)

The Log should contain all important information

**Comment by Rikshy** [comment]
hi there! 
thanks for the report and sorry for the inconvenience.

the log really did contain all i need. This should only effect Pink Beams and those closest to pink

will upload a new version
