### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by karelmikie3** [TeamWizardry/TMT-Refraction#54]
Server crashes on startup

refraction: 1.12.2-1.9.1
librrianlib: 1.12.2-4.9
forgelin: 1.7.4
[crash](https://paste.ee/p/Kucgh)
[log](https://paste.ee/p/QOnKf)

**Comment by Rikshy** [comment]
hi, thanks for your reported!

tbh i didnt run a server test. will upload a new version shortly!
