### ISSUE TITLE
[1.12.2] crash with futurepack and question.

### ISSUE THREAD

**Issue by lampyr** [TeamWizardry/TMT-Refraction#56]
When i use the laser pen with furepack installed i crash.
log: https://gist.github.com/lampyr/bab0134d73c86b15e6c6188c564f3aeb

and without futurepack i burn using the laser pen. Why?
log: https://gist.github.com/lampyr/aee76cda3d10a43c2d656fc0528fba63

LibrarianLib: 4.9
Refraction: 1.9.2
futurepack: 26.3.210

If you want other stuff ask me.
It is my first issue created and i don't speak english very well.

**Comment by Rikshy** [comment]
Hi there, thanks for you report!

the logs you uploaded did not contain crashes.
In you minecraft folder should be a subfolder named "crash-reports" can you send me the one?

Burning on Laser Pen is definetly a bug, ill check that!

**Comment by lampyr** [comment]
crash log: https://gist.github.com/lampyr/6b8adb662da2b252a54d6236dae26daa

Do i have open a new issue in futurepack github?

**Comment by Rikshy** [comment]
let me have a look at it first :)

**Comment by Rikshy** [comment]
it reads like refraction is not involved. so yes please open one at feature packs github.

you can leave a link here after you opened it :)

**Comment by Rikshy** [comment]
thanks!

**Comment by mcenderdragon** [comment]
Is the EntityLaserPointer from this mod? I am the Dev of Futurepack and I am asking because this entityy returns null from getItemStackFromSlot(#EntityEquipmentSlot) and Futurepack has crashed, I dont know if this is also @nonnull because it is not annotaded but I guess every ItemStack should be nonnull.

**Comment by Rikshy** [comment]
yea the laserpointer is from this mod, i might have forgotten this during the port! i'll look into it

**Comment by Rikshy** [comment]
okay, fixed in the last commit, will reupload a version!

https://github.com/TeamWizardry/TMT-Refraction/commit/2ed4a6393d0ffa114e8b431f3185224f17c9942e

**Comment by Rikshy** [comment]
please tell me if it is fixed.

should be available in a while

**Comment by lampyr** [comment]
thank you very much it is fixed.
