### ISSUE TITLE
Dropped items on pink laser crashes the game

### ISSUE THREAD

**Issue by fluid-uu-matter** [TeamWizardry/TMT-Refraction#57]

**Comment by fluid-uu-matter** [comment]
in 1.12.2 version, the pink laser which is supposed to place blocks causes a game crash when a item is dropped on. `---- Minecraft Crash Report ----
// There are four lights!

Time: 2018-08-23 09:23:00 CST
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.minecraft.world.World.isOutsideBuildHeight(World.java:224)
    at net.minecraft.world.World.getTileEntity(World.java:2381)
    at com.teamwizardry.refraction.common.effect.EffectPlace.runEntity(EffectPlace.java:64)
    at com.teamwizardry.refraction.api.beam.Effect.addEntity(Effect.java:137)
    at com.teamwizardry.refraction.api.beam.EffectTracker.lambda$tick$4(EffectTracker.java:116)
    at java.util.Collection.removeIf(Unknown Source)
    at com.teamwizardry.refraction.api.beam.EffectTracker.tick(EffectTracker.java:87)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1394_EffectTracker_tick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_121, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1980977024 bytes (1889 MB) / 8469348352 bytes (8077 MB) up to 8469348352 bytes (8077 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8139m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D3 109 mods loaded, 108 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State         | ID                                | Version           | Source                                          | Signature                                |
       |:------------- |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAAAAAA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.4.2705-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAA | forge                             | 14.23.4.2705      | forge-1.12.2-14.23.4.2705-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAA | creativecoredummy                 | 1.0.0             | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | itemphysic                        | 1.4.0             | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | micdoodlecore                     |                   | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | opencomputers|core                | 1.7.2.67          | minecraft.jar                                   | None                                     |
       | UCHIJAAAAAAAA | appliedenergistics2               | rv5-stable-11     | appliedenergistics2-rv5-stable-11.jar           | None                                     |
       | UCHIJAAAAAAAA | bdlib                             | 1.14.3.10         | bdlib-1.14.3.10-mc1.12.2.jar                    | None                                     |
       | UCHIJAAAAAAAA | ae2stuff                          | 0.7.0.4           | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
       | UCHIJAAAAAAAA | mdecore                           | 1.12-1.0          | mdecore-1.12-1.0.jar                            | None                                     |
       | UCHIJAAAAAAAA | autooredictconv                   | 1.12-1.0          | autooredictconv-1.12-1.0.jar                    | None                                     |
       | UCHIJAAAAAAAA | psi                               | r1.1-59           | Psi-r1.1-59.jar                                 | None                                     |
       | UCHIJAAAAAAAA | autoreglib                        | 1.3-16            | AutoRegLib-1.3-16.jar                           | None                                     |
       | UCHIJAAAAAAAA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
       | UCHIJAAAAAAAA | betterbuilderswands               | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
       | UCHIJAAAAAAAA | buildcraftlib                     | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftcore                    | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftbuilders                | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftenergy                  | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftfactory                 | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftrobotics                | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcrafttransport               | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | buildcraftsilicon                 | 7.99.17           | buildcraft-7.99.17.jar                          | None                                     |
       | UCHIJAAAAAAAA | codechickenlib                    | 3.1.8.341         | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAAAAAA | chickenchunks                     | 2.4.1.71          | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAAAAAA | ctm                               | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
       | UCHIJAAAAAAAA | chisel                            | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
       | UCHIJAAAAAAAA | chiselsandbits                    | 14.9              | chiselsandbits-14.9.jar                         | None                                     |
       | UCHIJAAAAAAAA | redstoneflux                      | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | cofhcore                          | 4.5.2             | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
       | UCHIJAAAAAAAA | cofhworld                         | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | crafttweaker                      | 4.1.6             | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
       | UCHIJAAAAAAAA | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
       | UCHIJAAAAAAAA | mtlib                             | 3.0.5             | MTLib-3.0.5.jar                                 | None                                     |
       | UCHIJAAAAAAAA | modtweaker                        | 4.0.12            | modtweaker-4.0.12.jar                           | None                                     |
       | UCHIJAAAAAAAA | jei                               | 4.8.5.159         | jei_1.12.2-4.8.5.159.jar                        | None                                     |
       | UCHIJAAAAAAAA | crafttweakerjei                   | 2.0.0             | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
       | UCHIJAAAAAAAA | creativecore                      | 1.9.9             | CreativeCore_v1.9.26_mc1.12.2.jar               | None                                     |
       | UCHIJAAAAAAAA | cyclicmagic                       | 1.15.12           | Cyclic-1.12.2-1.15.12.jar                       | None                                     |
       | UCHIJAAAAAAAA | endercore                         | 1.12.2-0.5.37     | EnderCore-1.12.2-0.5.37.jar                     | None                                     |
       | UCHIJAAAAAAAA | thermalfoundation                 | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | thermalexpansion                  | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | enderio                           | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationtic             | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderiobase                       | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderioconduits                   | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsappliedenergistics | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsopencomputers      | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsrefinedstorage     | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | ic2                               | 2.8.16-ex112      | industrialcraft-2-2.8.16-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
       | UCHIJAAAAAAAA | forestry                          | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationforestry        | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | mantle                            | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21.jar                        | None                                     |
       | UCHIJAAAAAAAA | tconstruct                        | 1.12.2-2.10.1.84  | TConstruct-1.12.2-2.10.1.84.jar                 | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationticlate         | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderiomachines                   | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderiopowertools                 | 5.0.31            | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
       | UCHIJAAAAAAAA | enderstorage                      | 2.4.0.122         | EnderStorage-1.12-2.4.0.122-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAAAAAA | energyconverters                  | 1.0.1.2           | energyconverters_1.12.1-1.0.1.2.jar             | None                                     |
       | UCHIJAAAAAAAA | extracells                        | 2.5.13            | ExtraCells-1.12.2-2.5.13a56.jar                 | None                                     |
       | UCHIJAAAAAAAA | golems                            | 7.0.0-beta1       | ExtraGolems-1.12-7.0.0-beta1.4.jar              | None                                     |
       | UCHIJAAAAAAAA | extrautils2                       | 1.0               | extrautils2-1.12-1.7.6.jar                      | None                                     |
       | UCHIJAAAAAAAA | flatcoloredblocks                 | mc1.12-6.6        | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
       | UCHIJAAAAAAAA | forgelin                          | 1.6.0             | Forgelin-1.6.0.jar                              | None                                     |
       | UCHIJAAAAAAAA | galacticraftcore                  | 4.0.1.168         | GalacticraftCore-1.12.2-4.0.1.168.jar           | None                                     |
       | UCHIJAAAAAAAA | galacticraftplanets               | 4.0.1.168         | Galacticraft-Planets-1.12.2-4.0.1.168.jar       | None                                     |
       | UCHIJAAAAAAAA | gendustry                         | 1.6.5.8           | gendustry-1.6.5.8-mc1.12.2.jar                  | None                                     |
       | UCHIJAAAAAAAA | advgenerators                     | 0.9.20.9          | generators-0.9.20.9-mc1.12.2.jar                | None                                     |
       | UCHIJAAAAAAAA | guideapi                          | 1.12-2.1.5-60     | Guide-API-1.12-2.1.5-60.jar                     | None                                     |
       | UCHIJAAAAAAAA | teslacorelib                      | 1.0.13            | tesla-core-lib-1.12-1.0.13.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.8.11-147.jar       | None                                     |
       | UCHIJAAAAAAAA | jeibees                           | 0.9.0.5           | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
       | UCHIJAAAAAAAA | loottweaker                       | 0.0.7             | LootTweaker-1.12.2-0.0.7.jar                    | None                                     |
       | UCHIJAAAAAAAA | jeresources                       | 0.8.5.27          | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
       | UCHIJAAAAAAAA | refraction                        | 1.9               | refraction-1.12.2-1.9.5.jar                     | None                                     |
       | UCHIJAAAAAAAA | librarianlib                      | 4.12              | librarianlib-1.12.2-4.12.jar                    | None                                     |
       | UCHIJAAAAAAAA | lootbags                          | 2.5.7             | LootBags-1.12.2-2.5.7.jar                       | None                                     |
       | UCHIJAAAAAAAA | mcjtylib_ng                       | 3.0.3             | mcjtylib-1.12-3.0.3.jar                         | None                                     |
       | UCHIJAAAAAAAA | mtrm                              | 1.2.2.30          | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar      | None                                     |
       | UCHIJAAAAAAAA | naturescompass                    | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
       | UCHIJAAAAAAAA | nbtedit                           | $version          | NBTEdit-0.7.jar                                 | None                                     |
       | UCHIJAAAAAAAA | opencomputers                     | 1.7.2.67          | OpenComputers-MC1.12.2-1.7.2.67.jar             | None                                     |
       | UCHIJAAAAAAAA | p455w0rdslib                      | 2.0.29            | p455w0rdslib-1.12-2.0.29.jar                    | None                                     |
       | UCHIJAAAAAAAA | redstonearsenal                   | 2.5.1             | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | redstoneigniter                   | 0.1               | redstoneigniter-0.1b.jar                        | None                                     |
       | UCHIJAAAAAAAA | rftools                           | 7.55              | rftools-1.12-7.55.jar                           | None                                     |
       | UCHIJAAAAAAAA | rftoolscontrol                    | 1.9.1             | rftoolsctrl-1.12-1.9.1.jar                      | None                                     |
       | UCHIJAAAAAAAA | rftoolsdim                        | 5.60              | rftoolsdim-1.12-5.60.jar                        | None                                     |
       | UCHIJAAAAAAAA | shulkerbox                        | 1.3.0             | shulkerbox-1.3.0.jar                            | None                                     |
       | UCHIJAAAAAAAA | simplyjetpacks                    | 2.2.4.34          | SimplyJetpacks2-1.12.2-2.2.4.34.jar             | None                                     |
       | UCHIJAAAAAAAA | stacksize                         | 1.1               | stacksize-1.12.2-1.0.jar                        | None                                     |
       | UCHIJAAAAAAAA | theoneprobe                       | 1.4.21            | theoneprobe-1.12-1.4.21.jar                     | None                                     |
       | UCHIJAAAAAAAA | thermalcultivation                | 0.3.0             | ThermalCultivation-1.12.2-0.3.0.7-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | thermaldynamics                   | 2.5.1             | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | thermalinnovation                 | 0.3.0             | ThermalInnovation-1.12.2-0.3.0.7-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAAAAAA | bspkrscore                        | at_0.9            | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
       | UCHIJAAAAAAAA | treecapitator                     | at_0.9            | Treecapitator-1.12-at_0.9a.jar                  | None                                     |
       | UCHIJAAAAAAAA | vanillafix                        | 1.0.9-97          | VanillaFix-1.0.9-97.jar                         | None                                     |
       | UCHIJAAAAAAAA | wanionlib                         | 1.12.2-1.5        | WanionLib-1.12.2-1.5.jar                        | None                                     |
       | UCHIJAAAAAAAA | wct                               | 3.9.62            | WirelessCraftingTerminal-1.12.2-3.9.62.jar      | None                                     |
       | UCHIJAAAAAAAA | woot                              | 1.12.2-1.0.1      | woot-1.12.2-1.0.1.jar                           | None                                     |
       | UCHIJAAAAAAAA | immersiveengineering              | 0.12-84           | ImmersiveEngineering-0.12-84.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCHIJAAAAAAAA | industrialwires                   | 1.7-28            | IndustrialWires-1.7-28.jar                      | 7e11c175d1e24007afec7498a1616bef0000027d |
       | UCHIJAAAAAAAA | librarianliblate                  | 4.12              | librarianlib-1.12.2-4.12.jar                    | None                                     |
       | UCHIJAAAAAAAA | teslacorelib_registries           | 1.0.13            | tesla-core-lib-1.12-1.0.13.jar                  | None                                     |
       | UCHIJAAAAAAAA | unidict                           | 1.12.2-2.4c       | UniDict-1.12.2-2.4c.jar                         | None                                     |
       | UD            | mdecore-core                      | 1.0               | minecraft.jar                                   | None                                     |
  Loaded coremods (and transformers): EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      IELoadingPlugin (ImmersiveEngineering-0.12-84-core.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.6.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.12.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.14_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.26_mc1.12.2.jar)
                                        
                                      MDECore-Core (mdecore-1.12-1.0.jar)
                                        com.mattdahepic.mdecore.asm.TickrateTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.168.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  List of loaded APIs: * appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
                       * Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
                       * BuildCraftAPI|blocks (1.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|boards (2.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|core (2.2) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|crops (1.1) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|enums (1.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|events (2.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|facades (1.1) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|filler (5.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|fuels (2.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|gates (4.1) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|items (1.1) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|library (2.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|lists (1.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|power (1.3) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|recipes (3.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|robotics (3.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|statements (1.1) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|tiles (1.2) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|tools (1.0) from buildcraft-7.99.17.jar
                       * BuildCraftAPI|transport (5.0) from buildcraft-7.99.17.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
                       * ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.9.jar
                       * cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.2.19-universal.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
                       * enderioapi (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.31.jar
                       * ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * Galacticraft API (1.1) from GalacticraftCore-1.12.2-4.0.1.168.jar
                       * gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
                       * Guide-API|API (2.0.0) from Guide-API-1.12-2.1.5-60.jar
                       * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-84.jar
                       * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-84.jar
                       * industrialforegoingapi (4) from industrialforegoing-1.12.2-1.8.11-147.jar
                       * jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.159.jar
                       * opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
                       * ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
                       * PsiAPI (6) from Psi-r1.1-59.jar
                       * refraction_api (5) from refraction-1.12.2-1.9.5.jar
                       * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.21.jar
                       * wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.62.jar
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Refraction (refraction)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
`

**Comment by murapix** [comment]
Put this crash report in a pastebin, not just plain text here.

Aside from that, this should be a relatively simple thing to fix.

**Comment by Snownee** [comment]
Can confirm this issue:
https://paste.dimdev.org/honefaziga.mccrash
