### ISSUE TITLE
Assembly table leaves fake item

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#6]
If you use a hopper to take out a output item it will leave a ghost item on the assembly table. (Can be removed with right click)

**Comment by yrsegal** [comment]
@LordSaad44 to fix this, onContentsChanged in the iitemhandler mark dirty.

**Comment by LordSaad44** [comment]
@yrsegal didn't work.

**Comment by LordSaad44** [comment]
I might remove the capabilities from it to force it to work. Idk... Or copy something from botania perhaps....

**Comment by yrsegal** [comment]
:I that's not how it works

i'll look at it...

**Comment by LordSaad44** [comment]
Fixed.
