### ISSUE TITLE
crashed when launch

### ISSUE THREAD

**Issue by alpha8196** [TeamWizardry/TMT-Refraction#8]
on refraction 1.1 and forge 2185
bug report : 
[http://pastebin.com/PTyQTc8t](url)

**Comment by murapix** [comment]
@yrsegal can you take a look at this? I think it may be another one of those LibLib errors

**Comment by Eladkay** [comment]
goddammit wire

**Comment by LordSaad44** [comment]
@alpha8196 1.1 is outdated. Current version is 1.2 and liblib is severely outdated. 1.3 should be out in a couple of hours as well. Update both.
