### ISSUE TITLE
Magnifier not making beam?

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#9]
Did something change or is this a bug?
http://i.imgur.com/9izSwd4.png

**Comment by thecodewarrior** [comment]
I'm not sure, @LordSaad44 did you test the magnifiers before releasing? 

...Not that I'm any better at testing things before release, in fact I'm much much worse.

**Comment by LordSaad44** [comment]
Odd... Are you able to reproduce it?
Can you please take another shot of that image from another angle?

It should be working...

**Comment by LordSaad44** [comment]
@Rucoon  I'm unable to reproduce it.

**Comment by Rucoon** [comment]
Just made a fresh mutiMC instance and it is working so I guess it was a other mod breaking something, feel free to close this.
